name: Continous Integration

on:
  push:
    branches:
      - main
      - test-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar dependencias
      uses:
      run: |
        npm install

    - name: Pruebas
      run: |
        npm run test